### ISSUE TITLE
swagger codegen fails due to java exception

### ISSUE THREAD

**Issue by vnugent** [hawkular/hawkular-metrics#173]
generate spec file
```
<hawkular-metric api>  mvn -Pdocgen
```
swagger codegen
```
java   -jar modules/swagger-codegen-distribution/target/swagger-codegen-distribution-2.1.2-M1.jar \
-i ../hawkular-metrics/api/metrics-api-jaxrs/generated/swagger-ui/service.json -l java \
-o ../hawkular-metrics-java/codegen
```
output
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from ../hawkular-metrics/api/metrics-api-jaxrs/generated/swagger-ui/service.json
reading from ../hawkular-metrics/api/metrics-api-jaxrs/generated/swagger-ui/service.json
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Interval.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/MetricId.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Metric.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/TagRequest.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/AggregatedValue.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Map.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/AggregationTemplate.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/UUID.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Error.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/AvailabilityMetric.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/NumericMetric.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/NumericData.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Availability.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/List.java
writing file ../hawkular-metrics-java/codegen/src/main/java/io/swagger/client/model/Tenant.java
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.wordnik.swagger.codegen.DefaultCodegen.snakeCase(DefaultCodegen.java:315)
	at com.wordnik.swagger.codegen.DefaultCodegen.toApiVarName(DefaultCodegen.java:138)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:117)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
```

**Comment by vnugent** [comment]
@burmanm

**Comment by burmanm** [comment]
This seems to be a bug in the swagger-codegen. I'll open an issue there.

**Comment by burmanm** [comment]
https://github.com/swagger-api/swagger-codegen/issues/495

**Comment by jkandasa** [comment]
applied patch from https://github.com/swagger-api/swagger-codegen/issues/495
still getting exception, but now it's from `initialCaps` method

```java
java -jar /tmp/swagger-codegen/modules/swagger-codegen-distribution/target/swagger-codegen-distribution-2.1.2-M1.jar -i api/metrics-api-jaxrs/generated/swagger-ui/service.json -l java -o api/metrics-api-jaxrs/generated/codegen/
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from api/metrics-api-jaxrs/generated/swagger-ui/service.json
reading from api/metrics-api-jaxrs/generated/swagger-ui/service.json
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Availability.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/NumericMetric.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/NumericData.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/AggregationTemplate.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Error.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/AggregatedValue.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/MetricId.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/TagRequest.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Tenant.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/AvailabilityMetric.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Metric.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/List.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/UUID.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Map.java
writing file api/metrics-api-jaxrs/generated/codegen//src/main/java/io/swagger/client/model/Interval.java
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at com.wordnik.swagger.codegen.DefaultCodegen.initialCaps(DefaultCodegen.java:320)
	at com.wordnik.swagger.codegen.DefaultCodegen.toApiFilename(DefaultCodegen.java:134)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:121)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
```
